# Generated by Django 3.2.12 on 2025-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_downloads', models.IntegerField(default=0)),
                ('weekly_downloads', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('contributors', models.IntegerField(default=0)),
                ('contributions', models.IntegerField(default=0)),
                ('days_since_last_release', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
    ]
